export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_SORT = 'CHANGE_SORT';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const DELETE_FROM_FAVORITES = 'DELETE_FROM_FAVORITES';
